// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Dashboard
void ui_Dashboard_screen_init(void);
lv_obj_t *ui_Dashboard;
lv_obj_t *ui_LeftContainer;
lv_obj_t *ui_pvContainer;
lv_obj_t *ui_Image6;
lv_obj_t *ui_pvLabel;
lv_obj_t *ui_pv1Label;
lv_obj_t *ui_pv2Label;
lv_obj_t *ui_batteryContainer;
lv_obj_t *ui_batteryTemperatureLabel;
lv_obj_t *ui_Image10;
lv_obj_t *ui_socLabel;
lv_obj_t *ui_batteryPowerLabel;
lv_obj_t *ui_loadContainer;
lv_obj_t *ui_Image8;
lv_obj_t *ui_loadPowerLabel;
lv_obj_t *ui_gridContainer;
lv_obj_t *ui_Image9;
lv_obj_t *ui_feedInPowerLabel;
lv_obj_t *ui_Container14;
lv_obj_t *ui_Image7;
lv_obj_t *ui_selfUsePercentLabel;
lv_obj_t *ui_inverterContainer;
lv_obj_t *ui_inverterTemperatureLabel;
lv_obj_t *ui_Image5;
lv_obj_t *ui_inverterPowerLabel;
lv_obj_t *ui_inverterPowerL1Label;
lv_obj_t *ui_inverterPowerL2Label;
lv_obj_t *ui_inverterPowerL3Label;
lv_obj_t *ui_RightContainer;
lv_obj_t *ui_TopRightContainer;
lv_obj_t *ui_Container15;
lv_obj_t *ui_Image11;
lv_obj_t *ui_Label14;
lv_obj_t *ui_Label15;
lv_obj_t *ui_Container16;
lv_obj_t *ui_Image12;
lv_obj_t *ui_Label16;
lv_obj_t *ui_Label17;
lv_obj_t *ui_Container17;
lv_obj_t *ui_Image13;
lv_obj_t *ui_Label18;
lv_obj_t *ui_Label19;
lv_obj_t *ui_Container18;
lv_obj_t *ui_Image14;
lv_obj_t *ui_Label21;
lv_obj_t *ui_Label22;
lv_obj_t *ui_statusLabel;
lv_obj_t *ui_Spinner1;
lv_obj_t *ui_TopBottomContainer;
lv_obj_t *ui_Chart1;
lv_obj_t *ui____initial_actions0;
const lv_img_dsc_t *ui_imgset_2097694489[1] = {&ui_img_2000019334};
const lv_img_dsc_t *ui_imgset_1565640187[1] = {&ui_img_1516017106};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Dashboard_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Dashboard);
}
