// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
lv_obj_t *ui_Splash;
lv_obj_t *ui_Image1;
lv_obj_t *ui_fwVersionLabel;
lv_obj_t *ui_ESPIdLabel;
lv_obj_t *ui_splashLabel;
// CUSTOM VARIABLES

// SCREEN: ui_Dashboard
void ui_Dashboard_screen_init(void);
lv_obj_t *ui_Dashboard;
lv_obj_t *ui_LeftContainer;
lv_obj_t *ui_pvContainer;
lv_obj_t *ui_Container11;
lv_obj_t *ui_pvLabel;
lv_obj_t *ui_pvUnitLabel;
lv_obj_t *ui_Container1;
lv_obj_t *ui_pvStringsContainer;
lv_obj_t *ui_Container13;
lv_obj_t *ui_pv1Label;
lv_obj_t *ui_pv1UnitLabel;
lv_obj_t *ui_Container19;
lv_obj_t *ui_pv2Label;
lv_obj_t *ui_pv2UnitLabel;
lv_obj_t *ui_pvStringsContainer1;
lv_obj_t *ui_Container18;
lv_obj_t *ui_pv3Label;
lv_obj_t *ui_pv3UnitLabel;
lv_obj_t *ui_Container31;
lv_obj_t *ui_pv4Label;
lv_obj_t *ui_pv4UnitLabel;
lv_obj_t *ui_Image6;
lv_obj_t *ui_batteryContainer;
lv_obj_t *ui_Container23;
lv_obj_t *ui_socLabel;
lv_obj_t *ui_socLabel1;
lv_obj_t *ui_Container24;
lv_obj_t *ui_Container2;
lv_obj_t *ui_batteryPowerLabel;
lv_obj_t *ui_batteryPowerUnitLabel;
lv_obj_t *ui_Container25;
lv_obj_t *ui_Image10;
lv_obj_t *ui_batteryTemperatureContainer;
lv_obj_t *ui_batteryTemperatureLabel;
lv_obj_t *ui_batteryTemperatureUnitLabel;
lv_obj_t *ui_loadContainer;
lv_obj_t *ui_Image8;
lv_obj_t *ui_Container14;
lv_obj_t *ui_shellyContainer;
lv_obj_t *ui_shellyCountLabel;
lv_obj_t *ui_Container32;
lv_obj_t *ui_shellyPowerLabel;
lv_obj_t *ui_shellyPowerUnitLabel;
lv_obj_t *ui_Container20;
lv_obj_t *ui_loadPowerLabel;
lv_obj_t *ui_loadPowerUnitLabel;
lv_obj_t *ui_gridContainer;
lv_obj_t *ui_Image9;
lv_obj_t *ui_Container4;
lv_obj_t *ui_Container22;
lv_obj_t *ui_feedInPowerLabel;
lv_obj_t *ui_feedInPowerUnitLabel;
lv_obj_t *ui_Container21;
lv_obj_t *ui_selfUsePercentLabel;
lv_obj_t *ui_selfUsePercentUnitLabel;
lv_obj_t *ui_inverterContainer;
lv_obj_t *ui_Image5;
lv_obj_t *ui_dongleFWVersion;
lv_obj_t *ui_inverterTemperatureContainer;
lv_obj_t *ui_inverterTemperatureLabel;
lv_obj_t *ui_inverterTemperatureUnitLabel;
lv_obj_t *ui_Container26;
lv_obj_t *ui_inverterPowerLabel;
lv_obj_t *ui_inverterPowerUnitLabel;
lv_obj_t *ui_Container33;
lv_obj_t *ui_Container29;
lv_obj_t *ui_inverterPowerL1Label;
lv_obj_t *ui_inverterPowerL1UnitLabel;
lv_obj_t *ui_Container3;
lv_obj_t *ui_inverterPowerL2Label;
lv_obj_t *ui_inverterPowerL2UnitLabel;
lv_obj_t *ui_Container28;
lv_obj_t *ui_inverterPowerL3Label;
lv_obj_t *ui_inverterPowerL3UnitLabel;
lv_obj_t *ui_statusLabel;
lv_obj_t *ui_RightContainer;
lv_obj_t *ui_TopRightContainer;
lv_obj_t *ui_pvStatsContainer;
lv_obj_t *ui_Container27;
lv_obj_t *ui_yieldTodayLabel;
lv_obj_t *ui_yieldTodayUnitLabel;
lv_obj_t *ui_Container5;
lv_obj_t *ui_yieldTotalLabel;
lv_obj_t *ui_yieldTotalUnitLabel;
lv_obj_t *ui_Image11;
lv_obj_t *ui_loadStatsContainer;
lv_obj_t *ui_Container8;
lv_obj_t *ui_loadTodayLabel;
lv_obj_t *ui_loadTodayUnitLabel;
lv_obj_t *ui_Container30;
lv_obj_t *ui_selfUseTodayLabel;
lv_obj_t *ui_selfUseTodayUnitLabel;
lv_obj_t *ui_Image13;
lv_obj_t *ui_batteryStatsContainer;
lv_obj_t *ui_Container6;
lv_obj_t *ui_batteryChargedTodayLabel;
lv_obj_t *ui_batteryChargedTodayUnitLabel;
lv_obj_t *ui_Container9;
lv_obj_t *ui_batteryDischargedTodayLabel;
lv_obj_t *ui_batteryDischargedTodayUnitLabel;
lv_obj_t *ui_Image12;
lv_obj_t *ui_gridStatsContainer;
lv_obj_t *ui_Container7;
lv_obj_t *ui_gridSellTodayLabel;
lv_obj_t *ui_gridSellTodayUnitLabel;
lv_obj_t *ui_Container10;
lv_obj_t *ui_gridBuyTodayLabel;
lv_obj_t *ui_gridBuyTodayUnitLabel;
lv_obj_t *ui_Image14;
lv_obj_t *ui_RightBottomContainer;
lv_obj_t *ui_Chart1;
// CUSTOM VARIABLES

// SCREEN: ui_WifiSetup
void ui_WifiSetup_screen_init(void);
lv_obj_t *ui_WifiSetup;
lv_obj_t *ui_Container12;
lv_obj_t *ui_Container16;
lv_obj_t *ui_Label1;
lv_obj_t *ui_wifiDongleRoller;
lv_obj_t *ui_Container15;
lv_obj_t *ui_Label2;
lv_obj_t *ui_wifiPassword;
lv_obj_t *ui_Container17;
lv_obj_t *ui_wifiSetupCompleteButton;
lv_obj_t *ui_Label3;
lv_obj_t *ui_Keyboard2;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Splash_screen_init();
ui_Dashboard_screen_init();
ui_WifiSetup_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Splash);
}
