// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#ifndef _SOLAXSTATIONLIVE_PROJECT_UI_H
#define _SOLAXSTATIONLIVE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_Splash.h"
#include "ui_Dashboard.h"
#include "ui_WifiSetup.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_logo_png);   // assets/logo.png
LV_IMG_DECLARE( ui_img_1516017106);   // assets/solar-panel-4.png
LV_IMG_DECLARE( ui_img_1279321064);   // assets/eco-battery.png
LV_IMG_DECLARE( ui_img_564643105);   // assets/eco-house-3.png
LV_IMG_DECLARE( ui_img_960241876);   // assets/power-plant.png
LV_IMG_DECLARE( ui_img_1061873486);   // assets/solar-inverter.png
LV_IMG_DECLARE( ui_img_ecovolter2_png);   // assets/ecovolter2.png
LV_IMG_DECLARE( ui_img_performance_png);   // assets/performance.png
LV_IMG_DECLARE( ui_img_settings_png);   // assets/settings.png

// FONTS
LV_FONT_DECLARE( ui_font_OpenSansExtraSmall);
LV_FONT_DECLARE( ui_font_OpenSansLarge);
LV_FONT_DECLARE( ui_font_OpenSansMedium);
LV_FONT_DECLARE( ui_font_OpenSansSmall);
LV_FONT_DECLARE( ui_font_OpenSansLargeBold);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
