// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#ifndef _SOLAXSTATIONLIVE_PROJECT_UI_H
#define _SOLAXSTATIONLIVE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_Splash
void ui_Splash_screen_init(void);
extern lv_obj_t *ui_Splash;
extern lv_obj_t *ui_MainContainer2;
extern lv_obj_t *ui_Label1;
// SCREEN: ui_Dashboard
void ui_Dashboard_screen_init(void);
extern lv_obj_t *ui_Dashboard;
extern lv_obj_t *ui_MainContainer;
extern lv_obj_t *ui_PVRowContainer;
extern lv_obj_t *ui_PVContainer;
extern lv_obj_t *ui_Image1;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_pvTodayYield;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_pvStringsLabel;
extern lv_obj_t *ui_pvLabel;
extern lv_obj_t *ui_PVContainer1;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_batteryChargedTodayLabel;
extern lv_obj_t *ui_batteryDischargedTodayLabel;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_batteryPowerLabel;
extern lv_obj_t *ui_socLabel;
extern lv_obj_t *ui_PVRowContainer1;
extern lv_obj_t *ui_PVContainer2;
extern lv_obj_t *ui_Image3;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_loadTodayLabel;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_l1Label;
extern lv_obj_t *ui_l2Label;
extern lv_obj_t *ui_l3Label;
extern lv_obj_t *ui_loadLabel;
extern lv_obj_t *ui_PVContainer3;
extern lv_obj_t *ui_Image4;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_gridSellTodayLabel;
extern lv_obj_t *ui_gridBuyTodayLabel;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_feedinLabel;
extern lv_obj_t *ui_statusLabel;
extern lv_obj_t *ui____initial_actions0;

LV_IMG_DECLARE( ui_img_80640877);   // assets/solar-panel-3.png
LV_IMG_DECLARE( ui_img_battery_png);   // assets/battery.png
LV_IMG_DECLARE( ui_img_880406665);   // assets/eco-house.png
LV_IMG_DECLARE( ui_img_2001872125);   // assets/power-line.png


LV_FONT_DECLARE( ui_font_RobotoMono32);
LV_FONT_DECLARE( ui_font_RobotoMono16);
LV_FONT_DECLARE( ui_font_RobotoMono12);


void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
