// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#include "ui.h"

// COMPONENT plugComponent

lv_obj_t *ui_plugComponent_create(lv_obj_t *comp_parent) {

lv_obj_t *cui_plugComponent;
cui_plugComponent = lv_obj_create(comp_parent);
lv_obj_remove_style_all(cui_plugComponent);
lv_obj_set_width( cui_plugComponent, lv_pct(100));
lv_obj_set_height( cui_plugComponent, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_plugComponent, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_plugComponent,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(cui_plugComponent, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( cui_plugComponent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(cui_plugComponent, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(cui_plugComponent, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(cui_plugComponent, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(cui_plugComponent, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_plugComponent, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_plugComponent, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_plugComponent, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(cui_plugComponent, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_plugComponent, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Container39;
cui_Container39 = lv_obj_create(cui_plugComponent);
lv_obj_remove_style_all(cui_Container39);
lv_obj_set_height( cui_Container39, 50);
lv_obj_set_width( cui_Container39, lv_pct(100));
lv_obj_set_x( cui_Container39, 1 );
lv_obj_set_y( cui_Container39, 0 );
lv_obj_set_align( cui_Container39, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Container39,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_Container39, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( cui_Container39, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(cui_Container39, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(cui_Container39, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(cui_Container39, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(cui_Container39, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Switch1;
cui_Switch1 = lv_switch_create(cui_Container39);
lv_obj_set_width( cui_Switch1, 50);
lv_obj_set_height( cui_Switch1, 25);
lv_obj_set_align( cui_Switch1, LV_ALIGN_CENTER );
lv_obj_add_state( cui_Switch1, LV_STATE_CHECKED | LV_STATE_DISABLED );     /// States

lv_obj_t *cui_Container38;
cui_Container38 = lv_obj_create(cui_Container39);
lv_obj_remove_style_all(cui_Container38);
lv_obj_set_height( cui_Container38, 50);
lv_obj_set_flex_grow( cui_Container38, 1);
lv_obj_set_align( cui_Container38, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Container38,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_Container38, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( cui_Container38, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

lv_obj_t *cui_Container36;
cui_Container36 = lv_obj_create(cui_Container38);
lv_obj_remove_style_all(cui_Container36);
lv_obj_set_height( cui_Container36, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( cui_Container36, 1);
lv_obj_set_align( cui_Container36, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Container36,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_Container36, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( cui_Container36, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(cui_Container36, -6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_Container36, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Container36, &ui_font_OpenSansSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_gridSellTodayLabel1;
cui_gridSellTodayLabel1 = lv_label_create(cui_Container36);
lv_obj_set_height( cui_gridSellTodayLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( cui_gridSellTodayLabel1, 2);
lv_obj_set_align( cui_gridSellTodayLabel1, LV_ALIGN_CENTER );
lv_label_set_long_mode(cui_gridSellTodayLabel1,LV_LABEL_LONG_SCROLL);
lv_label_set_text(cui_gridSellTodayLabel1,"45");
lv_obj_set_style_text_align(cui_gridSellTodayLabel1, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_gridSellTodayLabel1, &ui_font_OpenSansLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_gridSellTodayUnitLabel1;
cui_gridSellTodayUnitLabel1 = lv_label_create(cui_Container36);
lv_obj_set_height( cui_gridSellTodayUnitLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( cui_gridSellTodayUnitLabel1, 1);
lv_obj_set_align( cui_gridSellTodayUnitLabel1, LV_ALIGN_CENTER );
lv_label_set_text(cui_gridSellTodayUnitLabel1,"kWh");
lv_obj_set_style_text_align(cui_gridSellTodayUnitLabel1, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_gridSellTodayUnitLabel1, &ui_font_OpenSansExtraSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Container37;
cui_Container37 = lv_obj_create(cui_Container38);
lv_obj_remove_style_all(cui_Container37);
lv_obj_set_height( cui_Container37, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( cui_Container37, 1);
lv_obj_set_align( cui_Container37, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(cui_Container37,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(cui_Container37, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( cui_Container37, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(cui_Container37, -6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(cui_Container37, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_Container37, &ui_font_OpenSansSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_gridSellTodayLabel2;
cui_gridSellTodayLabel2 = lv_label_create(cui_Container37);
lv_obj_set_height( cui_gridSellTodayLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( cui_gridSellTodayLabel2, 2);
lv_obj_set_align( cui_gridSellTodayLabel2, LV_ALIGN_CENTER );
lv_label_set_long_mode(cui_gridSellTodayLabel2,LV_LABEL_LONG_SCROLL);
lv_label_set_text(cui_gridSellTodayLabel2,"45");
lv_obj_set_style_text_align(cui_gridSellTodayLabel2, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_gridSellTodayLabel2, &ui_font_OpenSansLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_gridSellTodayUnitLabel2;
cui_gridSellTodayUnitLabel2 = lv_label_create(cui_Container37);
lv_obj_set_height( cui_gridSellTodayUnitLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_grow( cui_gridSellTodayUnitLabel2, 1);
lv_obj_set_align( cui_gridSellTodayUnitLabel2, LV_ALIGN_CENTER );
lv_label_set_text(cui_gridSellTodayUnitLabel2,"kWh");
lv_obj_set_style_text_align(cui_gridSellTodayUnitLabel2, LV_TEXT_ALIGN_LEFT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(cui_gridSellTodayUnitLabel2, &ui_font_OpenSansExtraSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t *cui_Bar1;
cui_Bar1 = lv_bar_create(cui_plugComponent);
lv_bar_set_value(cui_Bar1,25,LV_ANIM_OFF);
lv_bar_set_start_value(cui_Bar1, 0, LV_ANIM_OFF);
lv_obj_set_height( cui_Bar1, 10);
lv_obj_set_width( cui_Bar1, lv_pct(100));
lv_obj_set_align( cui_Bar1, LV_ALIGN_CENTER );

lv_obj_t *cui_Label4;
cui_Label4 = lv_label_create(cui_plugComponent);
lv_obj_set_width( cui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( cui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( cui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(cui_Label4,"Solar Plug 3600W");
lv_obj_set_style_text_font(cui_Label4, &ui_font_OpenSansExtraSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_PLUGCOMPONENT_NUM);
children[UI_COMP_PLUGCOMPONENT_PLUGCOMPONENT] = cui_plugComponent;
children[UI_COMP_PLUGCOMPONENT_CONTAINER39] = cui_Container39;
children[UI_COMP_PLUGCOMPONENT_CONTAINER39_SWITCH1] = cui_Switch1;
children[UI_COMP_PLUGCOMPONENT_CONTAINER39_CONTAINER38] = cui_Container38;
children[UI_COMP_PLUGCOMPONENT_CONTAINER39_CONTAINER38_CONTAINER36] = cui_Container36;
children[UI_COMP_PLUGCOMPONENT_CONTAINER39_CONTAINER38_CONTAINER36_GRIDSELLTODAYLABEL1] = cui_gridSellTodayLabel1;
children[UI_COMP_PLUGCOMPONENT_CONTAINER39_CONTAINER38_CONTAINER36_GRIDSELLTODAYUNITLABEL1] = cui_gridSellTodayUnitLabel1;
children[UI_COMP_PLUGCOMPONENT_CONTAINER39_CONTAINER38_CONTAINER37] = cui_Container37;
children[UI_COMP_PLUGCOMPONENT_CONTAINER39_CONTAINER38_CONTAINER37_GRIDSELLTODAYLABEL2] = cui_gridSellTodayLabel2;
children[UI_COMP_PLUGCOMPONENT_CONTAINER39_CONTAINER38_CONTAINER37_GRIDSELLTODAYUNITLABEL2] = cui_gridSellTodayUnitLabel2;
children[UI_COMP_PLUGCOMPONENT_BAR1] = cui_Bar1;
children[UI_COMP_PLUGCOMPONENT_LABEL4] = cui_Label4;
lv_obj_add_event_cb(cui_plugComponent, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
lv_obj_add_event_cb(cui_plugComponent, del_component_child_event_cb, LV_EVENT_DELETE, children);
ui_comp_plugComponent_create_hook(cui_plugComponent);
return cui_plugComponent; 
}

