// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#include "ui.h"

void ui_ComponentsScreen_screen_init(void)
{
ui_ComponentsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ComponentsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_plugComponent = ui_plugComponent_create(ui_ComponentsScreen);
lv_obj_set_x( ui_plugComponent, -3 );
lv_obj_set_y( ui_plugComponent, 3 );
lv_obj_clear_flag( ui_plugComponent, LV_OBJ_FLAG_HIDDEN );    /// Flags



}
