// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#include "ui.h"

void ui_Dashboard_screen_init(void)
{
ui_Dashboard = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Dashboard, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Dashboard, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Dashboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MainContainer = lv_obj_create(ui_Dashboard);
lv_obj_remove_style_all(ui_MainContainer);
lv_obj_set_width( ui_MainContainer, lv_pct(100));
lv_obj_set_height( ui_MainContainer, lv_pct(100));
lv_obj_set_align( ui_MainContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_MainContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_MainContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_MainContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_MainContainer, lv_color_hex(0xFFFF00), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MainContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_MainContainer, lv_color_hex(0xFF8000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_main_stop(ui_MainContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_stop(ui_MainContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_dir(ui_MainContainer, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_MainContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_MainContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_MainContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_MainContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_MainContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_MainContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PVRowContainer = lv_obj_create(ui_MainContainer);
lv_obj_remove_style_all(ui_PVRowContainer);
lv_obj_set_width( ui_PVRowContainer, lv_pct(100));
lv_obj_set_flex_grow( ui_PVRowContainer, 1);
lv_obj_set_x( ui_PVRowContainer, -86 );
lv_obj_set_y( ui_PVRowContainer, -111 );
lv_obj_set_align( ui_PVRowContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PVRowContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PVRowContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PVRowContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_PVRowContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_PVRowContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PVContainer = lv_obj_create(ui_PVRowContainer);
lv_obj_remove_style_all(ui_PVContainer);
lv_obj_set_height( ui_PVContainer, lv_pct(100));
lv_obj_set_flex_grow( ui_PVContainer, 1);
lv_obj_set_align( ui_PVContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PVContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PVContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PVContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PVContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PVContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PVContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PVContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PVContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PVContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PVContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_PVContainer);
lv_img_set_src(ui_Image1, &ui_img_80640877);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image1, 29 );
lv_obj_set_y( ui_Image1, -90 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container6 = lv_obj_create(ui_PVContainer);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_height( ui_Container6, lv_pct(100));
lv_obj_set_flex_grow( ui_Container6, 1);
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container6,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container6, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pvStringsLabel = lv_label_create(ui_Container6);
lv_obj_set_width( ui_pvStringsLabel, lv_pct(100));
lv_obj_set_height( ui_pvStringsLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_pvStringsLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_pvStringsLabel,"123 W  |  123 W");
lv_obj_set_style_text_align(ui_pvStringsLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pvStringsLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pvLabel = lv_label_create(ui_Container6);
lv_obj_set_width( ui_pvLabel, lv_pct(100));
lv_obj_set_height( ui_pvLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_pvLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_pvLabel,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_pvLabel,"134 W");
lv_obj_set_style_text_align(ui_pvLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pvLabel, &ui_font_OpenSans48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PVContainer1 = lv_obj_create(ui_PVRowContainer);
lv_obj_remove_style_all(ui_PVContainer1);
lv_obj_set_height( ui_PVContainer1, lv_pct(100));
lv_obj_set_flex_grow( ui_PVContainer1, 1);
lv_obj_set_align( ui_PVContainer1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PVContainer1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PVContainer1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PVContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PVContainer1, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PVContainer1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PVContainer1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PVContainer1, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PVContainer1, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PVContainer1, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PVContainer1, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_PVContainer1);
lv_img_set_src(ui_Image2, &ui_img_battery_png);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image2, 29 );
lv_obj_set_y( ui_Image2, -90 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container1 = lv_obj_create(ui_PVContainer1);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_height( ui_Container1, lv_pct(100));
lv_obj_set_flex_grow( ui_Container1, 1);
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container1, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryPowerLabel = lv_label_create(ui_Container1);
lv_obj_set_width( ui_batteryPowerLabel, lv_pct(100));
lv_obj_set_height( ui_batteryPowerLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryPowerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryPowerLabel,"123 W  |  123 W");
lv_obj_set_style_text_align(ui_batteryPowerLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batteryPowerLabel, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_socLabel = lv_label_create(ui_Container1);
lv_obj_set_width( ui_socLabel, lv_pct(100));
lv_obj_set_height( ui_socLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_socLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_socLabel,"80 %");
lv_obj_set_style_text_align(ui_socLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_socLabel, &ui_font_OpenSans48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PVRowContainer1 = lv_obj_create(ui_MainContainer);
lv_obj_remove_style_all(ui_PVRowContainer1);
lv_obj_set_width( ui_PVRowContainer1, lv_pct(100));
lv_obj_set_flex_grow( ui_PVRowContainer1, 1);
lv_obj_set_x( ui_PVRowContainer1, -86 );
lv_obj_set_y( ui_PVRowContainer1, -111 );
lv_obj_set_align( ui_PVRowContainer1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PVRowContainer1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PVRowContainer1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PVRowContainer1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_PVRowContainer1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_PVRowContainer1, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PVContainer2 = lv_obj_create(ui_PVRowContainer1);
lv_obj_remove_style_all(ui_PVContainer2);
lv_obj_set_height( ui_PVContainer2, lv_pct(100));
lv_obj_set_flex_grow( ui_PVContainer2, 1);
lv_obj_set_align( ui_PVContainer2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PVContainer2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PVContainer2, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PVContainer2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PVContainer2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PVContainer2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PVContainer2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PVContainer2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PVContainer2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PVContainer2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PVContainer2, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_img_create(ui_PVContainer2);
lv_img_set_src(ui_Image3, &ui_img_880406665);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image3, 29 );
lv_obj_set_y( ui_Image3, -90 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container2 = lv_obj_create(ui_PVContainer2);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_height( ui_Container2, lv_pct(100));
lv_obj_set_flex_grow( ui_Container2, 1);
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_l1Label = lv_label_create(ui_Container2);
lv_obj_set_width( ui_l1Label, lv_pct(100));
lv_obj_set_height( ui_l1Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_l1Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_l1Label,"123 W");
lv_obj_set_style_text_align(ui_l1Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_l1Label, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_l2Label = lv_label_create(ui_Container2);
lv_obj_set_width( ui_l2Label, lv_pct(100));
lv_obj_set_height( ui_l2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_l2Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_l2Label,"123 W");
lv_obj_set_style_text_align(ui_l2Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_l2Label, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_l3Label = lv_label_create(ui_Container2);
lv_obj_set_width( ui_l3Label, lv_pct(100));
lv_obj_set_height( ui_l3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_l3Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_l3Label,"123 W");
lv_obj_set_style_text_align(ui_l3Label, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_l3Label, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_loadLabel = lv_label_create(ui_Container2);
lv_obj_set_width( ui_loadLabel, lv_pct(100));
lv_obj_set_height( ui_loadLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_loadLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_loadLabel,"123 W");
lv_obj_set_style_text_align(ui_loadLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_loadLabel, &ui_font_OpenSans48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PVContainer3 = lv_obj_create(ui_PVRowContainer1);
lv_obj_remove_style_all(ui_PVContainer3);
lv_obj_set_height( ui_PVContainer3, lv_pct(100));
lv_obj_set_flex_grow( ui_PVContainer3, 1);
lv_obj_set_align( ui_PVContainer3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_PVContainer3,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_PVContainer3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_PVContainer3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_PVContainer3, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_PVContainer3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_PVContainer3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_PVContainer3, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_PVContainer3, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_PVContainer3, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_PVContainer3, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_PVContainer3, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_PVContainer3, 12, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image4 = lv_img_create(ui_PVContainer3);
lv_img_set_src(ui_Image4, &ui_img_2001872125);
lv_obj_set_width( ui_Image4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image4, 29 );
lv_obj_set_y( ui_Image4, -90 );
lv_obj_set_align( ui_Image4, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image4, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image4, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container4 = lv_obj_create(ui_PVContainer3);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_height( ui_Container4, lv_pct(100));
lv_obj_set_flex_grow( ui_Container4, 1);
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container4, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container4, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label9 = lv_label_create(ui_Container4);
lv_obj_set_width( ui_Label9, lv_pct(100));
lv_obj_set_height( ui_Label9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label9,"123 W  |  123 W");
lv_obj_set_style_text_align(ui_Label9, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Label9, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_feedinLabel = lv_label_create(ui_Container4);
lv_obj_set_width( ui_feedinLabel, lv_pct(100));
lv_obj_set_height( ui_feedinLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_feedinLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_feedinLabel,"356 W");
lv_obj_set_style_text_align(ui_feedinLabel, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_feedinLabel, &ui_font_OpenSans48, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_statusLabel = lv_label_create(ui_MainContainer);
lv_obj_set_width( ui_statusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_statusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_statusLabel, -6 );
lv_obj_set_y( ui_statusLabel, -16 );
lv_obj_set_align( ui_statusLabel, LV_ALIGN_CENTER );
lv_obj_set_style_text_font(ui_statusLabel, &ui_font_OpenSans12, LV_PART_MAIN| LV_STATE_DEFAULT);

}
