// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#include "ui.h"

void ui_Dashboard_screen_init(void)
{
ui_Dashboard = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Dashboard, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM );    /// Flags
lv_obj_set_scrollbar_mode(ui_Dashboard, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_scroll_dir(ui_Dashboard, LV_DIR_VER);
lv_obj_set_flex_flow(ui_Dashboard,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Dashboard, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_radius(ui_Dashboard, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Dashboard, lv_color_hex(0xA7C7E7), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Dashboard, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Dashboard, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Dashboard, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Dashboard, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Dashboard, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Dashboard, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Dashboard, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LeftContainer = lv_obj_create(ui_Dashboard);
lv_obj_remove_style_all(ui_LeftContainer);
lv_obj_set_height( ui_LeftContainer, lv_pct(100));
lv_obj_set_flex_grow( ui_LeftContainer, 1);
lv_obj_set_x( ui_LeftContainer, 3 );
lv_obj_set_y( ui_LeftContainer, -23 );
lv_obj_set_align( ui_LeftContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_LeftContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_LeftContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LeftContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LeftContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_LeftContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_LeftContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_LeftContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_LeftContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pvContainer = lv_obj_create(ui_LeftContainer);
lv_obj_remove_style_all(ui_pvContainer);
lv_obj_set_width( ui_pvContainer, lv_pct(33));
lv_obj_set_height( ui_pvContainer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_flex_flow(ui_pvContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_pvContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_pvContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_pvContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_pvContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_pvContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_pvContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_pvColor);
ui_object_set_themeable_style_property(ui_pvContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_pvColor);
lv_obj_set_style_border_width(ui_pvContainer, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_pvContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_pvContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_pvContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_pvContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_pvContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_pvContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_pvContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container11 = lv_obj_create(ui_pvContainer);
lv_obj_remove_style_all(ui_Container11);
lv_obj_set_width( ui_Container11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Container11, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container11, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container11,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container11, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container11, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_pvLabel = lv_label_create(ui_Container11);
lv_obj_set_width( ui_pvLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pvLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_pvLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_pvLabel,"1134");
lv_obj_set_style_text_align(ui_pvLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pvLabel, &ui_font_OpenSansLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pvUnitLabel = lv_label_create(ui_Container11);
lv_obj_set_width( ui_pvUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pvUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_pvUnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_pvUnitLabel,"W");
lv_obj_set_style_text_align(ui_pvUnitLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pvUnitLabel, &ui_font_OpenSansSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_pvContainer);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_height( ui_Container1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container13 = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_Container13);
lv_obj_set_width( ui_Container13, lv_pct(100));
lv_obj_set_height( ui_Container13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Container13, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container13,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container13, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container13, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container13, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pv1Label = lv_label_create(ui_Container13);
lv_obj_set_width( ui_pv1Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pv1Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_pv1Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_pv1Label,"5600");
lv_obj_set_style_text_align(ui_pv1Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pv1Label, &ui_font_OpenSansMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pv1UnitLabel = lv_label_create(ui_Container13);
lv_obj_set_width( ui_pv1UnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pv1UnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_pv1UnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_pv1UnitLabel,"W");
lv_obj_set_style_text_font(ui_pv1UnitLabel, &ui_font_OpenSansExtraSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container19 = lv_obj_create(ui_Container1);
lv_obj_remove_style_all(ui_Container19);
lv_obj_set_width( ui_Container19, lv_pct(100));
lv_obj_set_height( ui_Container19, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Container19, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container19,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container19, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container19, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container19, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container19, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pv2Label = lv_label_create(ui_Container19);
lv_obj_set_width( ui_pv2Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pv2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_pv2Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_pv2Label,"5600");
lv_obj_set_style_text_align(ui_pv2Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pv2Label, &ui_font_OpenSansMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_pv2UnitLabel = lv_label_create(ui_Container19);
lv_obj_set_width( ui_pv2UnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_pv2UnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_pv2UnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_pv2UnitLabel,"W");
lv_obj_set_style_text_align(ui_pv2UnitLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_pv2UnitLabel, &ui_font_OpenSansExtraSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image6 = lv_img_create(ui_pvContainer);
lv_img_set_src(ui_Image6, &ui_img_1516017106);
lv_obj_set_width( ui_Image6, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image6, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_Image6, -141 );
lv_obj_set_y( ui_Image6, -169 );
lv_obj_set_align( ui_Image6, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image6, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image6, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_batteryContainer = lv_obj_create(ui_LeftContainer);
lv_obj_remove_style_all(ui_batteryContainer);
lv_obj_set_width( ui_batteryContainer, lv_pct(32));
lv_obj_set_height( ui_batteryContainer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryContainer, LV_ALIGN_TOP_RIGHT );
lv_obj_set_flex_flow(ui_batteryContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_batteryContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_batteryContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_batteryContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_batteryContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_batteryContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_batteryContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_batteryColor);
ui_object_set_themeable_style_property(ui_batteryContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_batteryColor);
lv_obj_set_style_border_width(ui_batteryContainer, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_batteryContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_batteryContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_batteryContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_batteryContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_batteryContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_batteryContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_batteryContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container23 = lv_obj_create(ui_batteryContainer);
lv_obj_remove_style_all(ui_Container23);
lv_obj_set_width( ui_Container23, 100);
lv_obj_set_height( ui_Container23, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container23, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container23,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container23, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container23, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_socLabel = lv_label_create(ui_Container23);
lv_obj_set_width( ui_socLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_socLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_socLabel, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_socLabel,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_socLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_socLabel,"80");
lv_obj_set_style_text_font(ui_socLabel, &ui_font_OpenSansLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_socLabel1 = lv_label_create(ui_Container23);
lv_obj_set_width( ui_socLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_socLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_socLabel1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_socLabel1,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_socLabel1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_label_set_text(ui_socLabel1,"%");
lv_obj_set_style_text_font(ui_socLabel1, &ui_font_OpenSansSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container24 = lv_obj_create(ui_batteryContainer);
lv_obj_remove_style_all(ui_Container24);
lv_obj_set_width( ui_Container24, 100);
lv_obj_set_height( ui_Container24, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container24, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container24,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container24, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container24, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container2 = lv_obj_create(ui_Container24);
lv_obj_remove_style_all(ui_Container2);
lv_obj_set_width( ui_Container2, lv_pct(100));
lv_obj_set_height( ui_Container2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Container2, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container2, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container2, 4, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryPowerLabel = lv_label_create(ui_Container2);
lv_obj_set_width( ui_batteryPowerLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryPowerLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryPowerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryPowerLabel,"5600");
lv_obj_set_style_text_align(ui_batteryPowerLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batteryPowerLabel, &ui_font_OpenSansMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryPowerUnitLabel = lv_label_create(ui_Container2);
lv_obj_set_width( ui_batteryPowerUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryPowerUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryPowerUnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryPowerUnitLabel,"W");
lv_obj_set_style_text_font(ui_batteryPowerUnitLabel, &ui_font_OpenSansExtraSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container12 = lv_obj_create(ui_Container24);
lv_obj_remove_style_all(ui_Container12);
lv_obj_set_width( ui_Container12, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_Container12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Container12, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_flex_flow(ui_Container12,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_batteryTemperatureLabel = lv_label_create(ui_Container12);
lv_obj_set_width( ui_batteryTemperatureLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryTemperatureLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryTemperatureLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryTemperatureLabel,"56");
lv_obj_set_style_text_align(ui_batteryTemperatureLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_batteryTemperatureLabel, &ui_font_OpenSansMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryTemperatureUnitLabel = lv_label_create(ui_Container12);
lv_obj_set_width( ui_batteryTemperatureUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryTemperatureUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryTemperatureUnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_batteryTemperatureUnitLabel,"°C");
lv_obj_set_style_text_font(ui_batteryTemperatureUnitLabel, &ui_font_OpenSansExtraSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container25 = lv_obj_create(ui_batteryContainer);
lv_obj_remove_style_all(ui_Container25);
lv_obj_set_height( ui_Container25, 48);
lv_obj_set_width( ui_Container25, lv_pct(115));
lv_obj_set_align( ui_Container25, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Container25, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image10 = lv_img_create(ui_Container25);
lv_img_set_src(ui_Image10, &ui_img_1279321064);
lv_obj_set_width( ui_Image10, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image10, LV_SIZE_CONTENT);   /// 48
lv_obj_set_align( ui_Image10, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image10, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image10, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_loadContainer = lv_obj_create(ui_LeftContainer);
lv_obj_remove_style_all(ui_loadContainer);
lv_obj_set_width( ui_loadContainer, lv_pct(32));
lv_obj_set_height( ui_loadContainer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_loadContainer, LV_ALIGN_BOTTOM_LEFT );
lv_obj_set_flex_flow(ui_loadContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_loadContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_loadContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_loadContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_loadContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_loadContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_loadContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_loadColor);
ui_object_set_themeable_style_property(ui_loadContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_loadColor);
lv_obj_set_style_border_width(ui_loadContainer, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_loadContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_loadContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_loadContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_loadContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_loadContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_loadContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_loadContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image8 = lv_img_create(ui_loadContainer);
lv_img_set_src(ui_Image8, &ui_img_564643105);
lv_obj_set_width( ui_Image8, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image8, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_Image8, -141 );
lv_obj_set_y( ui_Image8, -169 );
lv_obj_set_align( ui_Image8, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image8, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image8, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container20 = lv_obj_create(ui_loadContainer);
lv_obj_remove_style_all(ui_Container20);
lv_obj_set_width( ui_Container20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Container20, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container20, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container20,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container20, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container20, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_loadPowerLabel = lv_label_create(ui_Container20);
lv_obj_set_width( ui_loadPowerLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_loadPowerLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_loadPowerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_loadPowerLabel,"3234");
lv_obj_set_style_text_font(ui_loadPowerLabel, &ui_font_OpenSansLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_loadPowerUnitLabel = lv_label_create(ui_Container20);
lv_obj_set_width( ui_loadPowerUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_loadPowerUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_loadPowerUnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_loadPowerUnitLabel,"W");
lv_obj_set_style_text_font(ui_loadPowerUnitLabel, &ui_font_OpenSansSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gridContainer = lv_obj_create(ui_LeftContainer);
lv_obj_remove_style_all(ui_gridContainer);
lv_obj_set_width( ui_gridContainer, lv_pct(32));
lv_obj_set_height( ui_gridContainer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_gridContainer, LV_ALIGN_BOTTOM_RIGHT );
lv_obj_set_flex_flow(ui_gridContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_gridContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_gridContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_gridContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_gridContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_gridContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_gridContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_gridColor);
ui_object_set_themeable_style_property(ui_gridContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_gridColor);
lv_obj_set_style_border_width(ui_gridContainer, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_gridContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_gridContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_gridContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_gridContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_gridContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_gridContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_gridContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image9 = lv_img_create(ui_gridContainer);
lv_img_set_src(ui_Image9, &ui_img_960241876);
lv_obj_set_width( ui_Image9, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image9, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_Image9, -141 );
lv_obj_set_y( ui_Image9, -169 );
lv_obj_set_align( ui_Image9, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image9, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image9, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container22 = lv_obj_create(ui_gridContainer);
lv_obj_remove_style_all(ui_Container22);
lv_obj_set_width( ui_Container22, 100);
lv_obj_set_height( ui_Container22, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container22, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container22,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container22, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container22, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_feedInPowerLabel = lv_label_create(ui_Container22);
lv_obj_set_width( ui_feedInPowerLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_feedInPowerLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_feedInPowerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_feedInPowerLabel,"1234");
lv_obj_set_style_text_font(ui_feedInPowerLabel, &ui_font_OpenSansLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_feedInPowerUnitLabel = lv_label_create(ui_Container22);
lv_obj_set_width( ui_feedInPowerUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_feedInPowerUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_feedInPowerUnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_feedInPowerUnitLabel,"W");
lv_obj_set_style_text_font(ui_feedInPowerUnitLabel, &ui_font_OpenSansSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container14 = lv_obj_create(ui_LeftContainer);
lv_obj_remove_style_all(ui_Container14);
lv_obj_set_width( ui_Container14, lv_pct(30));
lv_obj_set_height( ui_Container14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Container14, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_Container14,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container14, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container14, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container21 = lv_obj_create(ui_Container14);
lv_obj_remove_style_all(ui_Container21);
lv_obj_set_width( ui_Container21, 100);
lv_obj_set_height( ui_Container21, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_Container21, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container21,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container21, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_selfUsePercentLabel = lv_label_create(ui_Container21);
lv_obj_set_width( ui_selfUsePercentLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selfUsePercentLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_selfUsePercentLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_selfUsePercentLabel,"86");
ui_object_set_themeable_style_property(ui_selfUsePercentLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_loadColor);
ui_object_set_themeable_style_property(ui_selfUsePercentLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_loadColor);
lv_obj_set_style_text_font(ui_selfUsePercentLabel, &ui_font_OpenSansLarge, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selfUsePercentUnitLabel = lv_label_create(ui_Container21);
lv_obj_set_width( ui_selfUsePercentUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selfUsePercentUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_selfUsePercentUnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_selfUsePercentUnitLabel,"%");
lv_obj_set_style_text_font(ui_selfUsePercentUnitLabel, &ui_font_OpenSansSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image7 = lv_img_create(ui_Container14);
lv_img_set_src(ui_Image7, &ui_img_leaf_png);
lv_obj_set_width( ui_Image7, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image7, LV_SIZE_CONTENT);   /// 48
lv_obj_set_align( ui_Image7, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image7, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image7, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_inverterContainer = lv_obj_create(ui_LeftContainer);
lv_obj_remove_style_all(ui_inverterContainer);
lv_obj_set_width( ui_inverterContainer, lv_pct(32));
lv_obj_set_height( ui_inverterContainer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_inverterContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_inverterContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_inverterContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_inverterContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_inverterContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_inverterContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_inverterContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
ui_object_set_themeable_style_property(ui_inverterContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_inverterColor);
ui_object_set_themeable_style_property(ui_inverterContainer, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_inverterColor);
lv_obj_set_style_border_width(ui_inverterContainer, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_inverterContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_color(ui_inverterContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_inverterContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_inverterContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_inverterContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_inverterContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_inverterContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_inverterContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_inverterContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container4 = lv_obj_create(ui_inverterContainer);
lv_obj_remove_style_all(ui_Container4);
lv_obj_set_width( ui_Container4, lv_pct(100));
lv_obj_set_height( ui_Container4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Container4, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container4,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container4, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Image5 = lv_img_create(ui_Container4);
lv_img_set_src(ui_Image5, &ui_img_1061873486);
lv_obj_set_width( ui_Image5, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image5, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_Image5, -141 );
lv_obj_set_y( ui_Image5, -169 );
lv_obj_set_align( ui_Image5, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image5, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image5, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_inverterTemperatureLabel = lv_label_create(ui_Container4);
lv_obj_set_width( ui_inverterTemperatureLabel, lv_pct(100));
lv_obj_set_height( ui_inverterTemperatureLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_inverterTemperatureLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_inverterTemperatureLabel,"56°C");
lv_obj_set_style_text_align(ui_inverterTemperatureLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_inverterTemperatureLabel, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_inverterPowerLabel = lv_label_create(ui_inverterContainer);
lv_obj_set_width( ui_inverterPowerLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_inverterPowerLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_inverterPowerLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_inverterPowerLabel,"1234 W");
lv_obj_set_style_text_font(ui_inverterPowerLabel, &ui_font_RobotoMonoMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_inverterContainer);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, 100);
lv_obj_set_height( ui_Container3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_inverterPowerL1Label = lv_label_create(ui_Container3);
lv_obj_set_width( ui_inverterPowerL1Label, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_inverterPowerL1Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_inverterPowerL1Label, LV_ALIGN_RIGHT_MID );
lv_label_set_text(ui_inverterPowerL1Label,"245W");
lv_obj_set_style_text_align(ui_inverterPowerL1Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_inverterPowerL1Label, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_inverterPowerL2Label = lv_label_create(ui_Container3);
lv_obj_set_width( ui_inverterPowerL2Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_inverterPowerL2Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_inverterPowerL2Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_inverterPowerL2Label,"245W");
lv_obj_set_style_text_align(ui_inverterPowerL2Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_inverterPowerL2Label, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_inverterPowerL3Label = lv_label_create(ui_Container3);
lv_obj_set_width( ui_inverterPowerL3Label, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_inverterPowerL3Label, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_inverterPowerL3Label, LV_ALIGN_CENTER );
lv_label_set_text(ui_inverterPowerL3Label,"245W");
lv_obj_set_style_text_align(ui_inverterPowerL3Label, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_inverterPowerL3Label, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_statusLabel = lv_label_create(ui_inverterContainer);
lv_obj_set_width( ui_statusLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_statusLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_statusLabel, LV_ALIGN_BOTTOM_MID );
lv_obj_set_style_text_font(ui_statusLabel, &ui_font_RobotoMonoExtraSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_shellyContainer = lv_obj_create(ui_LeftContainer);
lv_obj_remove_style_all(ui_shellyContainer);
lv_obj_set_width( ui_shellyContainer, lv_pct(24));
lv_obj_set_height( ui_shellyContainer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_shellyContainer, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_shellyContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_shellyContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_shellyContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_shellyContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_shellyContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_shellyContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_shellyContainer, lv_color_hex(0xABABAB), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_shellyContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_shellyContainer, 3, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_shellyContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_shellyContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_shellyContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_shellyContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_shellyContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_shellyContainer, 1, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_shellyContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image2 = lv_img_create(ui_shellyContainer);
lv_img_set_src(ui_Image2, &ui_img_1337922523);
lv_obj_set_width( ui_Image2, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image2, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_Image2, -141 );
lv_obj_set_y( ui_Image2, -169 );
lv_obj_set_align( ui_Image2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image2, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_shellyCountLabel = lv_label_create(ui_shellyContainer);
lv_obj_set_width( ui_shellyCountLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_shellyCountLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_shellyCountLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_shellyCountLabel,"3/5");
lv_obj_set_style_text_font(ui_shellyCountLabel, &ui_font_RobotoMonoExtraSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_shellyPowerLabel1 = lv_label_create(ui_shellyContainer);
lv_obj_set_width( ui_shellyPowerLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_shellyPowerLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_shellyPowerLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_shellyPowerLabel1,"1234 W");
lv_obj_set_style_text_font(ui_shellyPowerLabel1, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_RightContainer = lv_obj_create(ui_Dashboard);
lv_obj_remove_style_all(ui_RightContainer);
lv_obj_set_height( ui_RightContainer, lv_pct(100));
lv_obj_set_flex_grow( ui_RightContainer, 1);
lv_obj_set_x( ui_RightContainer, -1 );
lv_obj_set_y( ui_RightContainer, 0 );
lv_obj_set_align( ui_RightContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_RightContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_RightContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_RightContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_RightContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_RightContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TopRightContainer = lv_obj_create(ui_RightContainer);
lv_obj_remove_style_all(ui_TopRightContainer);
lv_obj_set_width( ui_TopRightContainer, lv_pct(100));
lv_obj_set_flex_grow( ui_TopRightContainer, 2);
lv_obj_set_align( ui_TopRightContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_TopRightContainer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_TopRightContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_TopRightContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TopRightContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TopRightContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TopRightContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_TopRightContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_TopRightContainer, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container15 = lv_obj_create(ui_TopRightContainer);
lv_obj_remove_style_all(ui_Container15);
lv_obj_set_height( ui_Container15, lv_pct(100));
lv_obj_set_flex_grow( ui_Container15, 1);
lv_obj_set_x( ui_Container15, lv_pct(1) );
lv_obj_set_y( ui_Container15, lv_pct(1) );
lv_obj_set_flex_flow(ui_Container15,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container15, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Container15, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container15, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container15, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container15, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container15, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Container15, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container5 = lv_obj_create(ui_Container15);
lv_obj_remove_style_all(ui_Container5);
lv_obj_set_width( ui_Container5, lv_pct(100));
lv_obj_set_flex_grow( ui_Container5, 1);
lv_obj_set_align( ui_Container5, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container5,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container5, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_yieldTodayLabel = lv_label_create(ui_Container5);
lv_obj_set_width( ui_yieldTodayLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_yieldTodayLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_yieldTodayLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_yieldTodayLabel,"11");
lv_obj_set_style_text_font(ui_yieldTodayLabel, &ui_font_RobotoMonoMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_yieldTodayUnitLabel = lv_label_create(ui_Container5);
lv_obj_set_width( ui_yieldTodayUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_yieldTodayUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_yieldTodayUnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_yieldTodayUnitLabel,"kWh");
lv_obj_set_style_text_font(ui_yieldTodayUnitLabel, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_yieldTotalLabel = lv_label_create(ui_Container15);
lv_obj_set_width( ui_yieldTotalLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_yieldTotalLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_yieldTotalLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_yieldTotalLabel,"11 MWh");
lv_obj_set_style_text_align(ui_yieldTotalLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_yieldTotalLabel, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image11 = lv_img_create(ui_Container15);
lv_img_set_src(ui_Image11, &ui_img_1516017106);
lv_obj_set_width( ui_Image11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image11, -141 );
lv_obj_set_y( ui_Image11, -169 );
lv_obj_set_align( ui_Image11, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image11, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image11, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container17 = lv_obj_create(ui_TopRightContainer);
lv_obj_remove_style_all(ui_Container17);
lv_obj_set_height( ui_Container17, lv_pct(100));
lv_obj_set_flex_grow( ui_Container17, 1);
lv_obj_set_x( ui_Container17, lv_pct(1) );
lv_obj_set_y( ui_Container17, lv_pct(1) );
lv_obj_set_flex_flow(ui_Container17,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container17, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container17, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container17, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container17, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container17, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container17, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container17, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Container17, 4, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container17, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container8 = lv_obj_create(ui_Container17);
lv_obj_remove_style_all(ui_Container8);
lv_obj_set_width( ui_Container8, lv_pct(100));
lv_obj_set_flex_grow( ui_Container8, 1);
lv_obj_set_align( ui_Container8, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container8,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container8, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_loadTodayLabel = lv_label_create(ui_Container8);
lv_obj_set_width( ui_loadTodayLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_loadTodayLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_loadTodayLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_loadTodayLabel,"11");
lv_obj_set_style_text_font(ui_loadTodayLabel, &ui_font_RobotoMonoMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_loadTodayUnitLabel = lv_label_create(ui_Container8);
lv_obj_set_width( ui_loadTodayUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_loadTodayUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_loadTodayUnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_loadTodayUnitLabel,"kWh");
lv_obj_set_style_text_font(ui_loadTodayUnitLabel, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_selfUseTodayLabel = lv_label_create(ui_Container17);
lv_obj_set_width( ui_selfUseTodayLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_selfUseTodayLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_selfUseTodayLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_selfUseTodayLabel,"11%");
ui_object_set_themeable_style_property(ui_selfUseTodayLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR, _ui_theme_color_loadColor);
ui_object_set_themeable_style_property(ui_selfUseTodayLabel, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA, _ui_theme_alpha_loadColor);
lv_obj_set_style_text_align(ui_selfUseTodayLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_selfUseTodayLabel, &ui_font_RobotoMonoMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image13 = lv_img_create(ui_Container17);
lv_img_set_src(ui_Image13, &ui_img_564643105);
lv_obj_set_width( ui_Image13, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image13, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_Image13, -141 );
lv_obj_set_y( ui_Image13, -169 );
lv_obj_set_align( ui_Image13, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image13, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image13, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container16 = lv_obj_create(ui_TopRightContainer);
lv_obj_remove_style_all(ui_Container16);
lv_obj_set_height( ui_Container16, lv_pct(100));
lv_obj_set_flex_grow( ui_Container16, 1);
lv_obj_set_x( ui_Container16, lv_pct(1) );
lv_obj_set_y( ui_Container16, lv_pct(1) );
lv_obj_set_flex_flow(ui_Container16,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container16, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container16, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container16, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container16, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container16, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container16, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Container16, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container16, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container6 = lv_obj_create(ui_Container16);
lv_obj_remove_style_all(ui_Container6);
lv_obj_set_width( ui_Container6, 100);
lv_obj_set_flex_grow( ui_Container6, 1);
lv_obj_set_align( ui_Container6, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container6,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container6, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container6, -6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container6, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryChargedTodayLabel = lv_label_create(ui_Container6);
lv_obj_set_width( ui_batteryChargedTodayLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryChargedTodayLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryChargedTodayLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_batteryChargedTodayLabel,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_batteryChargedTodayLabel,"11");
lv_obj_set_style_text_font(ui_batteryChargedTodayLabel, &ui_font_RobotoMonoMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryChargedTodayUnitLabel = lv_label_create(ui_Container6);
lv_obj_set_width( ui_batteryChargedTodayUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryChargedTodayUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryChargedTodayUnitLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_batteryChargedTodayUnitLabel,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_batteryChargedTodayUnitLabel,"kWh");
lv_obj_set_style_text_font(ui_batteryChargedTodayUnitLabel, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container9 = lv_obj_create(ui_Container16);
lv_obj_remove_style_all(ui_Container9);
lv_obj_set_width( ui_Container9, 100);
lv_obj_set_flex_grow( ui_Container9, 1);
lv_obj_set_align( ui_Container9, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container9,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container9, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container9, -6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container9, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryDischargedTodayLabel = lv_label_create(ui_Container9);
lv_obj_set_width( ui_batteryDischargedTodayLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryDischargedTodayLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryDischargedTodayLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_batteryDischargedTodayLabel,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_batteryDischargedTodayLabel,"-11");
lv_obj_set_style_text_font(ui_batteryDischargedTodayLabel, &ui_font_RobotoMonoMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_batteryDischargedTodayUnitLabel = lv_label_create(ui_Container9);
lv_obj_set_width( ui_batteryDischargedTodayUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_batteryDischargedTodayUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_batteryDischargedTodayUnitLabel, LV_ALIGN_CENTER );
lv_label_set_long_mode(ui_batteryDischargedTodayUnitLabel,LV_LABEL_LONG_DOT);
lv_label_set_text(ui_batteryDischargedTodayUnitLabel,"kWh");
lv_obj_set_style_text_font(ui_batteryDischargedTodayUnitLabel, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image12 = lv_img_create(ui_Container16);
lv_img_set_src(ui_Image12, &ui_img_performance_png);
lv_obj_set_width( ui_Image12, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image12, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_Image12, -141 );
lv_obj_set_y( ui_Image12, -169 );
lv_obj_set_align( ui_Image12, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image12, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image12, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Container18 = lv_obj_create(ui_TopRightContainer);
lv_obj_remove_style_all(ui_Container18);
lv_obj_set_height( ui_Container18, lv_pct(100));
lv_obj_set_flex_grow( ui_Container18, 1);
lv_obj_set_x( ui_Container18, lv_pct(1) );
lv_obj_set_y( ui_Container18, lv_pct(1) );
lv_obj_set_flex_flow(ui_Container18,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container18, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container18, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Container18, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Container18, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Container18, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_Container18, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container18, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container18, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container18, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Container18, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container18, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container7 = lv_obj_create(ui_Container18);
lv_obj_remove_style_all(ui_Container7);
lv_obj_set_width( ui_Container7, lv_pct(100));
lv_obj_set_flex_grow( ui_Container7, 1);
lv_obj_set_align( ui_Container7, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container7,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container7, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container7, -6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container7, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Container7, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gridSellTodayLabel = lv_label_create(ui_Container7);
lv_obj_set_width( ui_gridSellTodayLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gridSellTodayLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_gridSellTodayLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_gridSellTodayLabel,"11");
lv_obj_set_style_text_font(ui_gridSellTodayLabel, &ui_font_RobotoMonoMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gridSellTodayUnitLabel = lv_label_create(ui_Container7);
lv_obj_set_width( ui_gridSellTodayUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gridSellTodayUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_gridSellTodayUnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_gridSellTodayUnitLabel,"kWh");
lv_obj_set_style_text_font(ui_gridSellTodayUnitLabel, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container10 = lv_obj_create(ui_Container18);
lv_obj_remove_style_all(ui_Container10);
lv_obj_set_width( ui_Container10, lv_pct(100));
lv_obj_set_flex_grow( ui_Container10, 1);
lv_obj_set_align( ui_Container10, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container10,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container10, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container10, -6, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container10, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Container10, &lv_font_montserrat_14, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gridBuyTodayLabel = lv_label_create(ui_Container10);
lv_obj_set_width( ui_gridBuyTodayLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gridBuyTodayLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_gridBuyTodayLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_gridBuyTodayLabel,"-11");
lv_obj_set_style_text_font(ui_gridBuyTodayLabel, &ui_font_RobotoMonoMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_gridBuyTodayUnitLabel = lv_label_create(ui_Container10);
lv_obj_set_width( ui_gridBuyTodayUnitLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_gridBuyTodayUnitLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_gridBuyTodayUnitLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_gridBuyTodayUnitLabel,"kWh");
lv_obj_set_style_text_font(ui_gridBuyTodayUnitLabel, &ui_font_RobotoMonoSmall, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image14 = lv_img_create(ui_Container18);
lv_img_set_src(ui_Image14, &ui_img_960241876);
lv_obj_set_width( ui_Image14, LV_SIZE_CONTENT);  /// 48
lv_obj_set_height( ui_Image14, LV_SIZE_CONTENT);   /// 48
lv_obj_set_x( ui_Image14, -141 );
lv_obj_set_y( ui_Image14, -169 );
lv_obj_set_align( ui_Image14, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image14, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image14, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_TopBottomContainer = lv_obj_create(ui_RightContainer);
lv_obj_remove_style_all(ui_TopBottomContainer);
lv_obj_set_width( ui_TopBottomContainer, lv_pct(100));
lv_obj_set_flex_grow( ui_TopBottomContainer, 3);
lv_obj_set_align( ui_TopBottomContainer, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_TopBottomContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_TopBottomContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_TopBottomContainer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_TopBottomContainer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_TopBottomContainer, 52, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_TopBottomContainer, 42, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_TopBottomContainer, 16, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_TopBottomContainer, 24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Chart1 = lv_chart_create(ui_TopBottomContainer);
lv_obj_set_width( ui_Chart1, lv_pct(100));
lv_obj_set_height( ui_Chart1, lv_pct(100));
lv_obj_set_align( ui_Chart1, LV_ALIGN_CENTER );
lv_chart_set_type( ui_Chart1, LV_CHART_TYPE_LINE);
lv_chart_set_point_count( ui_Chart1, 96);
lv_chart_set_range( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 15);
lv_chart_set_div_line_count( ui_Chart1, 5, 0);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_X, 0, 0, 5, 24, true, 32);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_PRIMARY_Y, 0, 0, 5, 2, true, 32);
lv_chart_set_axis_tick( ui_Chart1, LV_CHART_AXIS_SECONDARY_Y, 0, 0, 3, 2, true, 32);
lv_obj_set_style_bg_color(ui_Chart1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Chart1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Chart1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_set_style_line_width(ui_Chart1, 3, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_line_rounded(ui_Chart1, true, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_set_style_size(ui_Chart1, 0, LV_PART_INDICATOR| LV_STATE_DEFAULT);

lv_obj_set_style_text_color(ui_Chart1, lv_color_hex(0x000000), LV_PART_TICKS | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Chart1, 255, LV_PART_TICKS| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Chart1, &ui_font_RobotoMonoExtraSmall, LV_PART_TICKS| LV_STATE_DEFAULT);

}
