// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#ifndef UI_DASHBOARD_H
#define UI_DASHBOARD_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Dashboard
extern void ui_Dashboard_screen_init(void);
extern void ui_Dashboard_screen_destroy(void);
extern lv_obj_t *ui_Dashboard;
extern lv_obj_t *ui_LeftContainer;
extern lv_obj_t *ui_pvContainer;
extern lv_obj_t *ui_Container11;
extern lv_obj_t *ui_pvLabel;
extern lv_obj_t *ui_pvUnitLabel;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_pvStringsContainer;
extern lv_obj_t *ui_Container13;
extern lv_obj_t *ui_pv1Label;
extern lv_obj_t *ui_pv1UnitLabel;
extern lv_obj_t *ui_Container19;
extern lv_obj_t *ui_pv2Label;
extern lv_obj_t *ui_pv2UnitLabel;
extern lv_obj_t *ui_pvStringsContainer1;
extern lv_obj_t *ui_Container18;
extern lv_obj_t *ui_pv3Label;
extern lv_obj_t *ui_pv3UnitLabel;
extern lv_obj_t *ui_Container31;
extern lv_obj_t *ui_pv4Label;
extern lv_obj_t *ui_pv4UnitLabel;
extern lv_obj_t *ui_Image6;
extern lv_obj_t *ui_batteryContainer;
extern lv_obj_t *ui_Container23;
extern lv_obj_t *ui_socLabel;
extern lv_obj_t *ui_socLabel1;
extern lv_obj_t *ui_Container17;
extern lv_obj_t *ui_batteryTimeLabel;
extern lv_obj_t *ui_Container24;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_batteryPowerLabel;
extern lv_obj_t *ui_batteryPowerUnitLabel;
extern lv_obj_t *ui_Container25;
extern lv_obj_t *ui_Image10;
extern lv_obj_t *ui_batteryTemperatureContainer;
extern lv_obj_t *ui_batteryTemperatureLabel;
extern lv_obj_t *ui_batteryTemperatureUnitLabel;
extern lv_obj_t *ui_loadContainer;
extern lv_obj_t *ui_Image8;
extern lv_obj_t *ui_Container14;
extern lv_obj_t *ui_shellyContainer;
extern lv_obj_t *ui_shellyCountLabel;
extern lv_obj_t *ui_Container32;
extern lv_obj_t *ui_shellyPowerLabel;
extern lv_obj_t *ui_shellyPowerUnitLabel;
extern lv_obj_t *ui_Container20;
extern lv_obj_t *ui_loadPowerLabel;
extern lv_obj_t *ui_loadPowerUnitLabel;
extern lv_obj_t *ui_gridContainer;
extern lv_obj_t *ui_Image9;
extern lv_obj_t *ui_Container4;
extern lv_obj_t *ui_Container22;
extern lv_obj_t *ui_feedInPowerLabel;
extern lv_obj_t *ui_feedInPowerUnitLabel;
extern lv_obj_t *ui_Container21;
extern lv_obj_t *ui_selfUsePercentLabel;
extern lv_obj_t *ui_selfUsePercentUnitLabel;
extern lv_obj_t *ui_inverterContainer;
extern lv_obj_t *ui_Image5;
extern lv_obj_t *ui_dongleFWVersion;
extern lv_obj_t *ui_inverterTemperatureContainer;
extern lv_obj_t *ui_inverterTemperatureLabel;
extern lv_obj_t *ui_inverterTemperatureUnitLabel;
extern lv_obj_t *ui_Container26;
extern lv_obj_t *ui_inverterPowerLabel;
extern lv_obj_t *ui_inverterPowerUnitLabel;
extern lv_obj_t *ui_Container33;
extern lv_obj_t *ui_Container29;
extern lv_obj_t *ui_inverterPowerBar1;
extern lv_obj_t *ui_inverterPowerL1Label;
extern lv_obj_t *ui_inverterPowerL1UnitLabel;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_inverterPowerBar2;
extern lv_obj_t *ui_inverterPowerL2Label;
extern lv_obj_t *ui_inverterPowerL2UnitLabel;
extern lv_obj_t *ui_Container28;
extern lv_obj_t *ui_inverterPowerBar3;
extern lv_obj_t *ui_inverterPowerL3Label;
extern lv_obj_t *ui_inverterPowerL3UnitLabel;
extern lv_obj_t *ui_statusLabel;
extern lv_obj_t *ui_Container34;
extern lv_obj_t *ui_Image2;
extern lv_obj_t *ui_Container36;
extern lv_obj_t *ui_batteryPowerLabel2;
extern lv_obj_t *ui_batteryPowerUnitLabel2;
extern lv_obj_t *ui_Slider1;
extern lv_obj_t *ui_Switch1;
extern lv_obj_t *ui_RightContainer;
extern lv_obj_t *ui_TopRightContainer;
extern lv_obj_t *ui_pvStatsContainer;
extern lv_obj_t *ui_Container27;
extern lv_obj_t *ui_yieldTodayLabel;
extern lv_obj_t *ui_yieldTodayUnitLabel;
extern lv_obj_t *ui_Container5;
extern lv_obj_t *ui_yieldTotalLabel;
extern lv_obj_t *ui_yieldTotalUnitLabel;
extern lv_obj_t *ui_Image11;
extern lv_obj_t *ui_loadStatsContainer;
extern lv_obj_t *ui_Container8;
extern lv_obj_t *ui_loadTodayLabel;
extern lv_obj_t *ui_loadTodayUnitLabel;
extern lv_obj_t *ui_Container30;
extern lv_obj_t *ui_selfUseTodayLabel;
extern lv_obj_t *ui_selfUseTodayUnitLabel;
extern lv_obj_t *ui_Image13;
extern lv_obj_t *ui_batteryStatsContainer;
extern lv_obj_t *ui_Container6;
extern lv_obj_t *ui_batteryChargedTodayLabel;
extern lv_obj_t *ui_batteryChargedTodayUnitLabel;
extern lv_obj_t *ui_Container9;
extern lv_obj_t *ui_batteryDischargedTodayLabel;
extern lv_obj_t *ui_batteryDischargedTodayUnitLabel;
extern lv_obj_t *ui_Image12;
extern lv_obj_t *ui_gridStatsContainer;
extern lv_obj_t *ui_Container7;
extern lv_obj_t *ui_gridSellTodayLabel;
extern lv_obj_t *ui_gridSellTodayUnitLabel;
extern lv_obj_t *ui_Container10;
extern lv_obj_t *ui_gridBuyTodayLabel;
extern lv_obj_t *ui_gridBuyTodayUnitLabel;
extern lv_obj_t *ui_Image14;
extern lv_obj_t *ui_RightBottomContainer;
extern lv_obj_t *ui_Chart1;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

