// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#include "ui.h"

void ui_Splash_screen_init(void)
{
ui_Splash = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Splash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Splash,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Splash, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_row(ui_Splash, 32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Splash, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Splash);
lv_img_set_src(ui_Image1, &ui_img_logo_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 318
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 128
lv_obj_set_x( ui_Image1, 11 );
lv_obj_set_y( ui_Image1, -307 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_fwVersionLabel = lv_label_create(ui_Splash);
lv_obj_set_width( ui_fwVersionLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_fwVersionLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_fwVersionLabel, LV_ALIGN_BOTTOM_LEFT );
lv_label_set_text(ui_fwVersionLabel,"v0");
lv_obj_add_flag( ui_fwVersionLabel, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_set_style_text_font(ui_fwVersionLabel, &ui_font_OpenSansSmall, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_fwVersionLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_fwVersionLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_fwVersionLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_fwVersionLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ESPIdLabel = lv_label_create(ui_Splash);
lv_obj_set_width( ui_ESPIdLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ESPIdLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ESPIdLabel, LV_ALIGN_BOTTOM_RIGHT );
lv_label_set_text(ui_ESPIdLabel,"FAFAFAFAFA");
lv_obj_add_flag( ui_ESPIdLabel, LV_OBJ_FLAG_IGNORE_LAYOUT );   /// Flags
lv_obj_set_style_text_font(ui_ESPIdLabel, &ui_font_OpenSansSmall, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_left(ui_ESPIdLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_ESPIdLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_ESPIdLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_ESPIdLabel, 8, LV_PART_MAIN| LV_STATE_DEFAULT);

}
