// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#include "ui.h"

void ui_Splash_screen_init(void)
{
ui_Splash = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Splash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Splash,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Splash, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_row(ui_Splash, 32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Splash, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image1 = lv_img_create(ui_Splash);
lv_img_set_src(ui_Image1, &ui_img_logo_png);
lv_obj_set_width( ui_Image1, LV_SIZE_CONTENT);  /// 318
lv_obj_set_height( ui_Image1, LV_SIZE_CONTENT);   /// 128
lv_obj_set_x( ui_Image1, 11 );
lv_obj_set_y( ui_Image1, -307 );
lv_obj_set_align( ui_Image1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image1, LV_OBJ_FLAG_ADV_HITTEST );   /// Flags
lv_obj_clear_flag( ui_Image1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Spinner1 = lv_spinner_create(ui_Splash,1000,90);
lv_obj_set_width( ui_Spinner1, 80);
lv_obj_set_height( ui_Spinner1, 80);
lv_obj_set_x( ui_Spinner1, -277 );
lv_obj_set_y( ui_Spinner1, -48 );
lv_obj_set_align( ui_Spinner1, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Spinner1, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_clear_flag( ui_Spinner1, LV_OBJ_FLAG_CLICKABLE );    /// Flags

ui_object_set_themeable_style_property(ui_Spinner1, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_COLOR, _ui_theme_color_pvColor);
ui_object_set_themeable_style_property(ui_Spinner1, LV_PART_INDICATOR| LV_STATE_DEFAULT, LV_STYLE_ARC_OPA, _ui_theme_alpha_pvColor);

ui_Label2 = lv_label_create(ui_Splash);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label2, -287 );
lv_obj_set_y( ui_Label2, -87 );
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"www.solar-station.cz");
lv_obj_add_flag( ui_Label2, LV_OBJ_FLAG_HIDDEN );   /// Flags
lv_obj_set_style_text_font(ui_Label2, &ui_font_RobotoMonoMedium, LV_PART_MAIN| LV_STATE_DEFAULT);

}
