// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#include "ui.h"

const ui_theme_variable_t _ui_theme_color_loadColor[1] = {0x03AD36};
const ui_theme_variable_t _ui_theme_alpha_loadColor[1] = {255};

const ui_theme_variable_t _ui_theme_color_pvColor[1] = {0xFFD400};
const ui_theme_variable_t _ui_theme_alpha_pvColor[1] = {255};

const ui_theme_variable_t _ui_theme_color_batteryColor[1] = {0x779ECB};
const ui_theme_variable_t _ui_theme_alpha_batteryColor[1] = {255};

const ui_theme_variable_t _ui_theme_color_inverterColor[1] = {0xD3D3D3};
const ui_theme_variable_t _ui_theme_alpha_inverterColor[1] = {255};

const ui_theme_variable_t _ui_theme_color_gridColor[1] = {0xC25964};
const ui_theme_variable_t _ui_theme_alpha_gridColor[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;

void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

