// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#ifndef UI_WIFISETUP_H
#define UI_WIFISETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiSetup
extern void ui_WifiSetup_screen_init(void);
extern void ui_WifiSetup_screen_destroy(void);
extern lv_obj_t *ui_WifiSetup;
extern lv_obj_t *ui_Container12;
extern lv_obj_t *ui_Container16;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_wifiDropdown;
extern lv_obj_t *ui_wifiPassword;
extern lv_obj_t *ui_wifiSetupCompleteButton;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Container15;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_connectionTypeDropdown;
extern lv_obj_t *ui_inverterIP;
extern lv_obj_t *ui_inverterSN;
extern lv_obj_t *ui_Container21;
extern lv_obj_t *ui_ContainerGeneral;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_spotProviderDropdown;
extern lv_obj_t *ui_timeZoneDropdown;
extern lv_obj_t *ui_languageDropdown;
extern lv_obj_t *ui_displayTimeoutDropdown;
extern lv_obj_t *ui_keyboard;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

