// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#ifndef UI_WIFISETUP_H
#define UI_WIFISETUP_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WifiSetup
extern void ui_WifiSetup_screen_init(void);
extern void ui_WifiSetup_screen_destroy(void);
extern lv_obj_t *ui_WifiSetup;
extern lv_obj_t *ui_Container12;
extern lv_obj_t *ui_Container16;
extern lv_obj_t *ui_wifiContainer;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_wifiDongleRoller;
extern lv_obj_t *ui_wifiPasswordContainer;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_wifiPassword;
extern lv_obj_t *ui_Container15;
extern lv_obj_t *ui_dongleTypeContainer;
extern lv_obj_t *ui_Label5;
extern lv_obj_t *ui_connectionTypeDropdown;
extern lv_obj_t *ui_dongleIPContainer;
extern lv_obj_t *ui_Label4;
extern lv_obj_t *ui_inverterIP;
extern lv_obj_t *ui_wifiSetupCompleteButton;
extern lv_obj_t *ui_Label3;
extern lv_obj_t *ui_Keyboard2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

