// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#include "ui.h"

void ui_WifiSetup_screen_init(void)
{
ui_WifiSetup = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WifiSetup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_WifiSetup,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_WifiSetup, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_row(ui_WifiSetup, 32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_WifiSetup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container12 = lv_obj_create(ui_WifiSetup);
lv_obj_remove_style_all(ui_Container12);
lv_obj_set_width( ui_Container12, lv_pct(100));
lv_obj_set_flex_grow( ui_Container12, 1);
lv_obj_set_align( ui_Container12, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container12,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container12, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container12, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container12, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container12, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Container12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container12, 24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container16 = lv_obj_create(ui_Container12);
lv_obj_remove_style_all(ui_Container16);
lv_obj_set_height( ui_Container16, lv_pct(100));
lv_obj_set_flex_grow( ui_Container16, 1);
lv_obj_set_align( ui_Container16, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container16,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container16, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container16, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container16, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_Container16);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Wifi dongle:");

ui_wifiDongleRoller = lv_roller_create(ui_Container16);
lv_roller_set_options( ui_wifiDongleRoller, "SOLAX - SX12345678\nSOLAX - SX12345678\nGoodWe - Solar_1234567", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_wifiDongleRoller, lv_pct(100));
lv_obj_set_flex_grow( ui_wifiDongleRoller, 1);
lv_obj_set_x( ui_wifiDongleRoller, -1 );
lv_obj_set_y( ui_wifiDongleRoller, 0 );
lv_obj_set_align( ui_wifiDongleRoller, LV_ALIGN_CENTER );

ui_Container15 = lv_obj_create(ui_Container12);
lv_obj_remove_style_all(ui_Container15);
lv_obj_set_height( ui_Container15, lv_pct(100));
lv_obj_set_flex_grow( ui_Container15, 1);
lv_obj_set_x( ui_Container15, -1 );
lv_obj_set_y( ui_Container15, 0 );
lv_obj_set_align( ui_Container15, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container15,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container15, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Container15);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"WiFi password:");

ui_wifiPassword = lv_textarea_create(ui_Container15);
lv_obj_set_width( ui_wifiPassword, lv_pct(100));
lv_obj_set_height( ui_wifiPassword, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiPassword, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_wifiPassword,"Placeholder...");



ui_Keyboard2 = lv_keyboard_create(ui_WifiSetup);
lv_obj_set_width( ui_Keyboard2, lv_pct(100));
lv_obj_set_flex_grow( ui_Keyboard2, 1);
lv_obj_set_x( ui_Keyboard2, -165 );
lv_obj_set_y( ui_Keyboard2, 36 );
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_CENTER );

lv_keyboard_set_textarea(ui_Keyboard2,ui_wifiPassword);

}
