// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SolaxStationLive_Project

#include "ui.h"

lv_obj_t *ui_WifiSetup = NULL;lv_obj_t *ui_Container12 = NULL;lv_obj_t *ui_Container16 = NULL;lv_obj_t *ui_wifiContainer = NULL;lv_obj_t *ui_Label1 = NULL;lv_obj_t *ui_wifiDongleRoller = NULL;lv_obj_t *ui_wifiPasswordContainer = NULL;lv_obj_t *ui_Label2 = NULL;lv_obj_t *ui_wifiPassword = NULL;lv_obj_t *ui_Container15 = NULL;lv_obj_t *ui_dongleTypeContainer = NULL;lv_obj_t *ui_Label5 = NULL;lv_obj_t *ui_dongleType = NULL;lv_obj_t *ui_dongleIPContainer = NULL;lv_obj_t *ui_Label4 = NULL;lv_obj_t *ui_dongleIP = NULL;lv_obj_t *ui_wifiSetupCompleteButton = NULL;lv_obj_t *ui_Label3 = NULL;lv_obj_t *ui_Keyboard2 = NULL;
// event funtions

// build funtions

void ui_WifiSetup_screen_init(void)
{
ui_WifiSetup = lv_obj_create(NULL);
lv_obj_clear_flag( ui_WifiSetup, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_WifiSetup,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_WifiSetup, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_pad_row(ui_WifiSetup, 32, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_WifiSetup, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container12 = lv_obj_create(ui_WifiSetup);
lv_obj_remove_style_all(ui_Container12);
lv_obj_set_width( ui_Container12, lv_pct(100));
lv_obj_set_flex_grow( ui_Container12, 2);
lv_obj_set_align( ui_Container12, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container12,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Container12, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container12, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_Container12, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_Container12, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_Container12, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_Container12, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Container12, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container12, 24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container16 = lv_obj_create(ui_Container12);
lv_obj_remove_style_all(ui_Container16);
lv_obj_set_width( ui_Container16, 364);
lv_obj_set_height( ui_Container16, lv_pct(100));
lv_obj_set_align( ui_Container16, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container16,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container16, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container16, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container16, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container16, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_wifiContainer = lv_obj_create(ui_Container16);
lv_obj_remove_style_all(ui_wifiContainer);
lv_obj_set_width( ui_wifiContainer, lv_pct(100));
lv_obj_set_flex_grow( ui_wifiContainer, 1);
lv_obj_set_align( ui_wifiContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wifiContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_wifiContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_wifiContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_wifiContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_wifiContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label1 = lv_label_create(ui_wifiContainer);
lv_obj_set_width( ui_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label1,"Wifi dongle:");

ui_wifiDongleRoller = lv_roller_create(ui_wifiContainer);
lv_roller_set_options( ui_wifiDongleRoller, "SOLAX - SX12345678\nSOLAX - SX12345678\nGoodWe - Solar_1234567", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_wifiDongleRoller, lv_pct(100));
lv_obj_set_flex_grow( ui_wifiDongleRoller, 1);
lv_obj_set_x( ui_wifiDongleRoller, -1 );
lv_obj_set_y( ui_wifiDongleRoller, 0 );
lv_obj_set_align( ui_wifiDongleRoller, LV_ALIGN_CENTER );

ui_wifiPasswordContainer = lv_obj_create(ui_Container16);
lv_obj_remove_style_all(ui_wifiPasswordContainer);
lv_obj_set_width( ui_wifiPasswordContainer, lv_pct(100));
lv_obj_set_height( ui_wifiPasswordContainer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiPasswordContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_wifiPasswordContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_wifiPasswordContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_wifiPasswordContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_wifiPasswordContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_wifiPasswordContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_wifiPasswordContainer);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"WiFi password:");

ui_wifiPassword = lv_textarea_create(ui_wifiPasswordContainer);
lv_obj_set_width( ui_wifiPassword, lv_pct(100));
lv_obj_set_height( ui_wifiPassword, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_wifiPassword, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_wifiPassword,32);
lv_textarea_set_placeholder_text(ui_wifiPassword,"Placeholder...");

ui_Container15 = lv_obj_create(ui_Container12);
lv_obj_remove_style_all(ui_Container15);
lv_obj_set_width( ui_Container15, 364);
lv_obj_set_height( ui_Container15, lv_pct(100));
lv_obj_set_x( ui_Container15, -1 );
lv_obj_set_y( ui_Container15, 0 );
lv_obj_set_align( ui_Container15, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container15,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container15, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container15, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container15, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container15, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_dongleTypeContainer = lv_obj_create(ui_Container15);
lv_obj_remove_style_all(ui_dongleTypeContainer);
lv_obj_set_width( ui_dongleTypeContainer, lv_pct(100));
lv_obj_set_height( ui_dongleTypeContainer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dongleTypeContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_dongleTypeContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_dongleTypeContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_dongleTypeContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_dongleTypeContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_dongleTypeContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_dongleTypeContainer);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"Connection Type:");

ui_dongleType = lv_dropdown_create(ui_dongleTypeContainer);
lv_dropdown_set_options( ui_dongleType, "SOLAX\nVictron\nGoodWe\nSofar Solar\nDEYE" );
lv_obj_set_width( ui_dongleType, lv_pct(100));
lv_obj_set_height( ui_dongleType, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dongleType, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_dongleType, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_dongleIPContainer = lv_obj_create(ui_Container15);
lv_obj_remove_style_all(ui_dongleIPContainer);
lv_obj_set_width( ui_dongleIPContainer, lv_pct(100));
lv_obj_set_height( ui_dongleIPContainer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dongleIPContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_dongleIPContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_dongleIPContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_dongleIPContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_dongleIPContainer, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_dongleIPContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label4 = lv_label_create(ui_dongleIPContainer);
lv_obj_set_width( ui_Label4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label4,"Dongle IP:");

ui_dongleIP = lv_textarea_create(ui_dongleIPContainer);
lv_obj_set_width( ui_dongleIP, lv_pct(100));
lv_obj_set_height( ui_dongleIP, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_dongleIP, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_dongleIP,16);
lv_textarea_set_placeholder_text(ui_dongleIP,"Leave empty for autodetect ...");

ui_wifiSetupCompleteButton = lv_btn_create(ui_Container15);
lv_obj_set_height( ui_wifiSetupCompleteButton, 50);
lv_obj_set_width( ui_wifiSetupCompleteButton, lv_pct(100));
lv_obj_set_x( ui_wifiSetupCompleteButton, 348 );
lv_obj_set_y( ui_wifiSetupCompleteButton, -393 );
lv_obj_set_align( ui_wifiSetupCompleteButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_wifiSetupCompleteButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_wifiSetupCompleteButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Label3 = lv_label_create(ui_wifiSetupCompleteButton);
lv_obj_set_width( ui_Label3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label3,"OK");

ui_Keyboard2 = lv_keyboard_create(ui_WifiSetup);
lv_obj_set_height( ui_Keyboard2, 180);
lv_obj_set_width( ui_Keyboard2, lv_pct(100));
lv_obj_set_x( ui_Keyboard2, -165 );
lv_obj_set_y( ui_Keyboard2, 36 );
lv_obj_set_align( ui_Keyboard2, LV_ALIGN_CENTER );

lv_keyboard_set_textarea(ui_Keyboard2,ui_wifiPassword);

}

void ui_WifiSetup_screen_destroy(void)
{
   if (ui_WifiSetup) lv_obj_del(ui_WifiSetup);

// NULL screen variables
ui_WifiSetup= NULL;
ui_Container12= NULL;
ui_Container16= NULL;
ui_wifiContainer= NULL;
ui_Label1= NULL;
ui_wifiDongleRoller= NULL;
ui_wifiPasswordContainer= NULL;
ui_Label2= NULL;
ui_wifiPassword= NULL;
ui_Container15= NULL;
ui_dongleTypeContainer= NULL;
ui_Label5= NULL;
ui_dongleType= NULL;
ui_dongleIPContainer= NULL;
ui_Label4= NULL;
ui_dongleIP= NULL;
ui_wifiSetupCompleteButton= NULL;
ui_Label3= NULL;
ui_Keyboard2= NULL;

}
