// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 9.2.2
// Project name: SolaxStationLive_Project

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_LOADCOLOR 0
#define UI_THEME_COLOR_PVCOLOR 1
#define UI_THEME_COLOR_BATTERYCOLOR 2
#define UI_THEME_COLOR_INVERTERCOLOR 3
#define UI_THEME_COLOR_GRIDCOLOR 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_loadColor[1];
extern const ui_theme_variable_t _ui_theme_alpha_loadColor[1];

extern const ui_theme_variable_t _ui_theme_color_pvColor[1];
extern const ui_theme_variable_t _ui_theme_alpha_pvColor[1];

extern const ui_theme_variable_t _ui_theme_color_batteryColor[1];
extern const ui_theme_variable_t _ui_theme_alpha_batteryColor[1];

extern const ui_theme_variable_t _ui_theme_color_inverterColor[1];
extern const ui_theme_variable_t _ui_theme_alpha_inverterColor[1];

extern const ui_theme_variable_t _ui_theme_color_gridColor[1];
extern const ui_theme_variable_t _ui_theme_alpha_gridColor[1];

extern const uint32_t* ui_theme_colors[1];
extern const uint8_t* ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
